typedef float cnmgrMatrix4x4[4][4];

#define CNMGR_INTERNAL_TYPE_UBERMATRIX 1

#define CNMGR_NODE_TYPE_CAMERA 1
#define CNMGR_NODE_TYPE_MESH 2

#define CNMGR_NON_INDEXED_FLOAT_ARRAY 1

#define CNMGR_GL_UNIFORM_1F 0
#define CNMGR_GL_UNIFORM_2F 1
#define CNMGR_GL_UNIFORM_3F 2
#define CNMGR_GL_UNIFORM_4F 3
#define CNMGR_GL_UNIFORM_1I 4
#define CNMGR_GL_UNIFORM_2I 5
#define CNMGR_GL_UNIFORM_3I 6
#define CNMGR_GL_UNIFORM_4I 7
#define CNMGR_GL_UNIFORM_1UI 8
#define CNMGR_GL_UNIFORM_2UI 9
#define CNMGR_GL_UNIFORM_3UI 10
#define CNMGR_GL_UNIFORM_4UI 11
#define CNMGR_GL_UNIFORM_1FV 12
#define CNMGR_GL_UNIFORM_2FV 13
#define CNMGR_GL_UNIFORM_3FV 14
#define CNMGR_GL_UNIFORM_4FV 15
#define CNMGR_GL_UNIFORM_1IV 16
#define CNMGR_GL_UNIFORM_2IV 17
#define CNMGR_GL_UNIFORM_3IV 18
#define CNMGR_GL_UNIFORM_4IV 19
#define CNMGR_GL_UNIFORM_1UIV 20
#define CNMGR_GL_UNIFORM_2UIV 21
#define CNMGR_GL_UNIFORM_3UIV 22
#define CNMGR_GL_UNIFORM_4UIV 23
#define CNMGR_GL_UNIFORM_MATRIX_2FV 24
#define CNMGR_GL_UNIFORM_MATRIX_3FV 25
#define CNMGR_GL_UNIFORM_MATRIX_4FV 26
#define CNMGR_GL_UNIFORM_MATRIX_2X3FV 27
#define CNMGR_GL_UNIFORM_MATRIX_3X2FV 28
#define CNMGR_GL_UNIFORM_MATRIX_2X4FV 29
#define CNMGR_GL_UNIFORM_MATRIX_4X2FV 30
#define CNMGR_GL_UNIFORM_MATRIX_3X4FV 31
#define CNMGR_GL_UNIFORM_MATRIX_4X3FV 32